eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8764

spring:
  application:
    name: zuul

zuul:
  routes:
    user: /u/** #服务名：路径
    test-feign: /f/**
