server:
  port: 8763

eureka:
  client:
    service-url:
      default-zone: http:localhost:8761/eureka/

spring:
  application:
    name: test-feign
  zipkin:
    base-url: http://localhost:9411

#打开断路器
feign:
  hystrix:
    enabled: true