spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/theLittleAnt/testSpringcloud.git
          search-paths: config-files
          username:
          password:
      label: master

server:
  port: 8765

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/



